### ISSUE TITLE
Possible Issue with `use_z_instead_ifft` feature in SE_NZC

### ISSUE THREAD

**Issue by denzchoe** [mhuser/scikit-rf#4]
As indicated in the title, 
https://github.com/scikit-rf/scikit-rf/blob/0d4b1a5bab8df3c0b6b89f7d639d98b7e1064bca/skrf/calibration/deembedding.py#L1280-L1292

```python
            for i in range(len(f)):
                ZL[i, :, :] = [
                    [z[i, 0, 0] + z[i, 1, 0], 2. * z[i, 1, 0]],
                    [2. * z[i, 1, 0], 2. * z[i, 1, 0]]
                              ]
                ZL[i, :, :] = [
                    [2. * z[i, 0, 1], 2. * z[i, 0, 1]],
                    [2. * z[i, 0, 1], z[i, 1, 1] + z[i, 0, 1]]
                              ]
                
                s_side1 = Network(frequency = s2xthru.frequency, z = ZL, z0 = self.z0)
                s_side2 = Network(frequency = s2xthru.frequency, z = ZR, z0 = self.z0)
                s_side2.flip() # FIX-2 is flipped in skrf
```

should be;

```python
            for i in range(len(f)):
                ZL[i, :, :] = [
                    [z[i, 0, 0] + z[i, 1, 0], 2. * z[i, 1, 0]],
                    [2. * z[i, 1, 0], 2. * z[i, 1, 0]]
                              ]
                ZL[i, :, :] = [
                    [2. * z[i, 0, 1], 2. * z[i, 0, 1]],
                    [2. * z[i, 0, 1], z[i, 1, 1] + z[i, 0, 1]]
                              ]
            # indentation was incorrectly inserted here previously. Fixed now  
            s_side1 = Network(frequency = s2xthru.frequency, z = ZL, z0 = self.z0)
            s_side2 = Network(frequency = s2xthru.frequency, z = ZR, z0 = self.z0)
            s_side2.flip() # FIX-2 is flipped in skrf
```

But even after I manually fixed it;
I still get the following error: `TypeError: len() of unsized object`
Have you managed to test it out?

**Comment by mhuser** [comment]
Good spot ! This indentation issue leaded the network to re-affect on each loop. Very inefficient (but should give correct results at the end).

I now also see I wrote **two time ZL** and **no ZR** on second statement. For this reason, ZR keep zeros.

> I still get the following error: TypeError: len() of unsized object
This is curious as it worked when I tested.
f is from `f = s2xthru.frequency.f` on line 1107

I should fix this and add capacity to force impedance.

**Comment by mhuser** [comment]
https://github.com/scikit-rf/scikit-rf/pull/708

**Comment by denzchoe** [comment]
> I now also see I wrote **two time ZL** and **no ZR** on second statement. For this reason, ZR keep zeros.

Oh yeah! I didn't even realise that. 
I tried changing it on my machine. Still getting error

```python
fix_z0_shape
    elif len(z0) == nports:

TypeError: len() of unsized object
```

**Comment by mhuser** [comment]
Right this sounds an issue with z0 being a scalar 😲 
Here is my test code, maybe interpolation get rid of this issue in my case by forcing `z0` into an array:

```
from matplotlib import pyplot as plt
import skrf as rf
from skrf.media import Coaxial
from skrf.calibration import IEEEP370_SE_NZC_2xThru
rf.stylely()

# load data
s2xthru = rf.Network('meas_s2xthru.s2p')

# new frequency axis
f_start = 0.01 # GHz
f_stop  = 50.  # GHz
n       = int(f_stop / f_start)
f_new   = rf.Frequency(f_start, f_stop, n, 'GHz')

# interpolate
s2xthru_i = s2xthru.interpolate(f_new)

# diagnostic
dm = IEEEP370_SE_NZC_2xThru(dummy_2xthru = s2xthru_i, name = '2xthru',
                            verbose = True)

dm_fft = IEEEP370_SE_NZC_2xThru(dummy_2xthru = s2xthru_i, name = '2xthru',
                            use_z_instead_ifft = True)

dm_forced = IEEEP370_SE_NZC_2xThru(dummy_2xthru = s2xthru_i, name = '2xthru',
                            forced_z11x = 48, verbose = True)
                            
#plot them all
plt.figure()
dm.s_side1.plot_s_db(0, 0, label = 'FIX-1, S11')
dm_fft.s_side1.plot_s_db(0, 0, label = 'FIX-1, S11, use_z_instead_ifft = True')
dm_forced.s_side1.plot_s_db(0, 0, label = 'FIX-1, S11, forced_z11x = 48')
```

**Comment by mhuser** [comment]
Are you using latest github master ? There was maybe some PRs related to Z transform and z0 recently.

**Comment by mhuser** [comment]
The z-transform did however output results that are even worse in the case of 2x-Tru:
![image](https://user-images.githubusercontent.com/8080934/173806231-5b22636f-6632-49d4-b20e-9c2149874d84.png)

I think it is really only intended for very shorts 2x-Thru when the standard algorithm fail to compute length and impedance.

**Comment by denzchoe** [comment]
> Are you using latest github master ? There was maybe some PRs related to Z transform and z0 recently.

Oh right. I just remembered this https://github.com/scikit-rf/scikit-rf/pull/705
Maybe that is the cause of it. I have checked.
Shape of the array seems alright though.
```python
np.shape(ZL)
(Out  [1]): (5000, 2, 2)
```

Seems like issue [PR#705](https://github.com/scikit-rf/scikit-rf/pull/705) might fix it. 
Let me try this later..

**Comment by denzchoe** [comment]
oh my .. v0.23 is quite a leap from 0.22.1.
There are too many dependencies. I cannot just do a simple copy and paste on 1 or 2 files inside skrf.
I am already bumping into 3 files requiring changes... better stop before I break something..
 
I will just have to wait for the official release on condaforge to test `use_z_instead_ifft`. Or when I figured out how to manually install it on my miniconda env via git without breaking anything... 

Though `forced_z11x` works!

**Comment by mhuser** [comment]
> Though `forced_z11x` works!

This sounds good! I think this will be a good option for moving your deembedding challenge forward.

I use this workflow (only for reference):

1. ~~fork scikit-rf/scikit-rf~~ (this step is only useful to later make commit and pull requests)
2. clone the repo locally using [github desktop](https://desktop.github.com/) application, latest master could then be fetched regularly
3. make conda use the clone instead of the officially released package.
`cd Documents\GitHub\scikit-rf\`
And with the prompt in the directory of the clone
`pip install -e .`

**Comment by denzchoe** [comment]
Usually I only download the official package on condaforge. I've tried manually installing pip packages in the past. (Not skrf); and it broke my conda env several times. Imagine having to painfully re-install Anaconda again and again (Long installation time). 
Couple of lessons learnt in data hygiene, clone stable env, use miniconda, and use official releases from Condaforge.

Let me bend this rule one time and test this then close this issue if everything is ok 😉

**Comment by denzchoe** [comment]
yup works fine now! No longer seeing `TypeError: len() of unsized object` errors. Master version fixed it.
Thanks!

**Comment by mhuser** [comment]
> I've tried manually installing pip packages in the past. (Not skrf); and it broke my conda env several times. Imagine having to painfully re-install Anaconda again and again (Long installation time).

I agree this is dangerous!
